[package]
name = "atelier_openapi"
description = "Rust native OpenAPI format for the AWS Smithy IDL."
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"
documentation = "https://docs.rs/atelier_openapi/"
repository = "https://github.com/johnstonskj/rust-atelier.git"
license = "MIT"
readme = "README.md"
publish = true

[package.metadata.docs.rs]
# This sets the default target to `x86_64-unknown-linux-gnu`
# and only builds that target for documentation.
targets = ["x86_64-unknown-linux-gnu"]
all-features = true

[dependencies]
atelier_core = { version = "~0.2", path = "../atelier-core" }
okapi = "0.7.0-rc.1"
serde_json = "1.0"

[dev-dependencies]
atelier_test = { version = "0.1", path = "../atelier-test" }
atelier_smithy = { version = "~0.2", path = "../atelier-smithy" }
atelier_json = { version = "~0.2", path = "../atelier-json" }
pretty_assertions = "1.1"